# All these parameters have to be fixed according to the specs. detailed in 852_Echo_Sounder_Kit_manual.pdf
# profundidad_minima --> eco sounder kit manual, pg 23: Byte 15 Profile Minimum Range Minimum range for profile point digitization
# 0 – 250  0 to 25 meters in 0.1 meter increments
# Byte 15 = min range in meters / 10
# profundidad_maxima ==> //Range: 5,10,20,30,40,50 in meters. Defined in the technical specs of the manufacturer 
# Start Gain: 0 to 40dB in 1 dB increments,
# longitud_pulso --> Byte 14 Pulse Length, Length of acoustic transmit pulse. 1-255. 1 to 255 micro sec in 1 micro sec increments
# The external trigger must be a 0 to 5 volt TTL pulse with a minimum length of 100 microseconds.
# Switch Delay: The echo sounder can be commanded to pause (from 0 to 510 msec). Before sending its return data to allow the commanding program enough time to setup for serial reception of the return data.
# 0 to 255 in 2 msec increments Byte 24 = delay_in_milliseconds/2 . Do not use a value of 253!
# //Data Points: 25=250 points 'IMX'

imagenex_echosounder/profundidad_maxima: 50.0
imagenex_echosounder/profundidad_minima: 0.5

imagenex_echosounder/ganancia: 19

imagenex_echosounder/longitud_pulso: 100
imagenex_echosounder/delay: 2
imagenex_echosounder/data_points: 25

